### ISSUE TITLE
Error setting up entry for hon

### ISSUE THREAD

**Issue by robb3rt-1337** [IoTLabs-pl/hon#12]
**Describe the bug**
After installing this git repo in my HACS and installing latest version (v0.14.0-beta.14), restarting HA, then I am unable to setup my Haier h0n account. The error I get to see in the error log;

`Logger: homeassistant.config_entries
Bron: config_entries.py:604
Eerst voorgekomen: 16:20:27 (1 gebeurtenissen)
Laatst gelogd: 16:20:27

Error setting up entry for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 38, in async_setup_entry
    hon = await Hon(
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 51, in setup
    async for a in Appliance.create_from_data(self._api, appliance_data):
  File "/usr/local/lib/python3.12/site-packages/pyhon/appliances/_base.py", line 84, in create_from_data
    await appliance.load_commands()
  File "/usr/local/lib/python3.12/site-packages/pyhon/appliances/_base.py", line 292, in load_commands
    self.commands, self.additional_data = loader(self, payload)
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/command_loader.py", line 37, in loader
    _clean_name(category_name): HonCommand(
                                ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/commands.py", line 37, in __init__
    self._load_parameters(attributes)
  File "/usr/local/lib/python3.12/site-packages/pyhon/commands.py", line 74, in _load_parameters
    self._create_parameters(data, name, key)
  File "/usr/local/lib/python3.12/site-packages/pyhon/commands.py", line 85, in _create_parameters
    self._rules.append(HonRuleSet(self, data["fixedValue"]))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 22, in __init__
    self._parse_rule(rule)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 32, in _parse_rule
    self._parse_conditions(param_key, trigger_key, trigger_data)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 54, in _parse_conditions
    self._parse_conditions(param_key, extra_key, extra_data, extra)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 54, in _parse_conditions
    self._parse_conditions(param_key, extra_key, extra_data, extra)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 43, in _parse_conditions
    for multi_trigger_value, param_data in trigger_data.items():
                                           ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'`

**Expected behavior**
Able to setup the account haha.

**Environment (please complete the following information):**
 - Home Assistant Version: 2024.9.1
 - hOn Integration Version v0.14.0-beta.14

**Comment by kubasaw** [comment]
Tracked here: https://github.com/IoTLabs-pl/pyhOn/issues/5
