### ISSUE TITLE
Error setting up new Entry

### ISSUE THREAD

**Issue by AquaXV** [IoTLabs-pl/hon#16]
When adding new account to the Integration the following error is logged:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 38, in async_setup_entry
    hon = await Hon(
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 51, in setup
    async for a in Appliance.create_from_data(self._api, appliance_data):
  File "/usr/local/lib/python3.12/site-packages/pyhon/appliances/_base.py", line 84, in create_from_data
    await appliance.load_commands()
  File "/usr/local/lib/python3.12/site-packages/pyhon/appliances/_base.py", line 292, in load_commands
    self.commands, self.additional_data = loader(self, payload)
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/command_loader.py", line 37, in loader
    _clean_name(category_name): HonCommand(
                                ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/commands.py", line 37, in __init__
    self._load_parameters(attributes)
  File "/usr/local/lib/python3.12/site-packages/pyhon/commands.py", line 74, in _load_parameters
    self._create_parameters(data, name, key)
  File "/usr/local/lib/python3.12/site-packages/pyhon/commands.py", line 85, in _create_parameters
    self._rules.append(HonRuleSet(self, data["fixedValue"]))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 22, in __init__
    self._parse_rule(rule)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 32, in _parse_rule
    self._parse_conditions(param_key, trigger_key, trigger_data)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 54, in _parse_conditions
    self._parse_conditions(param_key, extra_key, extra_data, extra)
  File "/usr/local/lib/python3.12/site-packages/pyhon/rules.py", line 43, in _parse_conditions
    for multi_trigger_value, param_data in trigger_data.items():
                                           ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
```

Setting pyhon to debug logging results in the following output:
```
2024-11-08 15:24:24.873 DEBUG (MainThread) [pyhon.apis.auth] Trying to retrieve Cognito token
2024-11-08 15:24:24.873 DEBUG (MainThread) [pyhon.apis.auth] Starting OAuth2 authorization
2024-11-08 15:24:25.796 DEBUG (MainThread) [pyhon.apis.auth] Logging in
2024-11-08 15:24:26.607 DEBUG (MainThread) [pyhon.apis.auth] Getting tokens
```

Running: 
HA: 2024.11
Haier hOn: 0.14.0-beta14
pyhOn: 0.18.0b3

**Comment by kubasaw** [comment]
Generally, at the moment i'm not able to debug this part of code: i dont understand logic of hOn rules well, but I will try to fix it in near future (after serious logic refactor). Thank you for reporting.
